### ISSUE TITLE
Radial Gradients when using a Mask does not work as anticipated

### ISSUE THREAD

**Issue by bcompter** [andymeneely/squib#127]
This may be a misunderstanding on my end but the following code does not look like I would expect.

```Ruby
require 'squib'

Squib::Deck.new do

  # Radial gradients look like this
  circle fill_color: '(200,200,0)(200,200,100) #ccc@0.0 #111@1.0', x: 200, y: 200, radius: 100, stroke_color: '#0000'
  png file: 'circle.png', x: 400, y: 100, height: 200, width: 200, mask: '(500,200,0)(500,200,100) #ccc@0.0 #111@1.0'

  save_png prefix: 'test_'
end
```

Looks like this when I would expect that the two circles would be similar.  The radial gradient is not even close to being centered in the masked circle.
![test_00](https://cloud.githubusercontent.com/assets/6876373/11983699/7dda6614-a983-11e5-9bce-16d714b4e3aa.png)

Thanks for your help.

**Comment by andymeneely** [comment]
How big is the original png file? Can you upload it for me?

**Comment by andymeneely** [comment]
Let me guess - 500x500? Yup it does have to do with the width/height scaling behavior combining with the coordinate system changing. Let me see what I can do about that.

**Comment by andymeneely** [comment]
As a workaround until then, you could:
  * scale your pngs to what you need (probably not the answer you want to hear), or 
  * scale your gradient coordinates. I haven't figured out the math for this just yet, but this appears to get your example back on track assuming a 500x500 `circle.png`:

```ruby
png file: 'circle.png', x: 400, y: 100, height: 200, width: 200, mask: "(650,350,0)(650,350,250) #ccc@0.0 #111@1.0"
```

**Comment by andymeneely** [comment]
Ok, turns out this fix is (initially) looking way easier than I thought it would be. I've started a fix in a new branch called `bug127`. 

I need to explore how much this may or may not break other code.

If you're feeling up to it, you could always point your Gemfile to the `bug127` branch and see if this gives you the expected behavior.

*My understanding of what's going on, for future posterity.* Linear and radial gradients rely on the user coordinate system, and often those are used in the midst of translations, rotates, etc. But Squib users can't be expected to scale their coordinates based on this assumption, so we have to set `Cairo::Pattern`'s  coordinate system to the `Cairo::Context`'s coordinate system (i.e. `matrix`). In doing that, Squib users use a consistent set of transformations.
