### ISSUE TITLE
"Rake" command

### ISSUE THREAD

**Issue by Timothep** [andymeneely/squib#186]
Hi there, and many thanks for the great tool! Just a short feedback from a usually-non-ruby-user, it took me  a while to understand that I "just" needed to call "rake" to trigger the creation process. This seems to be a ruby standard, but as a non ruby dev, I could not find it anywhere in the doc and had to process with trial and error. Did I overlook it somewhere?
Thanks

**Comment by andymeneely** [comment]
Ah, I mean "run" rake from the command line. So instead of typing `ruby deck.rb` on the command line, type `rake`. That will then look at the file called `Rakefile` in your project and run the tasks.

I'm in the process of documenting this exact thing better throughout the docs. Where was the confusing wording?

(Eventually, I'll document more of this here: http://squib.readthedocs.io/en/latest/guides/getting-started/part_3_workflows.html)

**Comment by Timothep** [comment]
Hi Andy, thanks for your reply. 

There was no confusing wording, I just couldn't find the command anywhere. 

I would have liked to have it at top level. After the Install&Update Step, I already have a running state, right? It would fit well to expand this section to "Install, Update and Run". Or at least in the "Hello World! Dissected"

Cheers,
Tim

**Comment by andymeneely** [comment]
Great!! Those are great places for it. Thanks for the note.

**Comment by andymeneely** [comment]
Just pushed some better explanation of this.
