### ISSUE TITLE
Empty cell in Excel leads to silent error

### ISSUE THREAD

**Issue by Timothep** [andymeneely/squib#199]
Hi there, I am seeing a strange behavior. Don't know if it's due to what I wrote or a real bug. Let's consider the following table (in Excel)

Name | Effect 
-------|-------
Sword | Slash
Shield |

and the following call in my deck.rb file:

>  svg layout: data['Effect']

**Error**: If I leave the effect for the 'shield' empty (as in the table above), the none of the effects are rendered and thus none of the "Effect" SVGs displayed. The sword's effect neither.
**Solution**: If I set a simple 'x' in the shield's effect cell it is displayed everywhere

Nota: I added a simple no-op rule in my yaml file for 'x'

> x: # placeholder
>   x: 0

Any idea if this is supposed to be this way?

**Comment by andymeneely** [comment]
So "Slash" doesn't get rendered? That surprises me. What else is in your layout?

The placeholder thing shouldn't be a factor.

The Effect for Shield shouldn't render because that would be equivalent to:

```ruby
svg #does nothing - on purpose
```
(The reason for that second thing this is to make it easy to _not_ draw things when you don't want them drawn. The nil case doesn't complain, it just does nothing.)

Now, if you reference a layout and the layout does NOT exist - it'll complain about that. Or if you give wrong inputs. This is keeping with the [All Parameters are Optional](http://squib.readthedocs.io/en/v0.13/parameters.html) philosophy.

**Comment by Timothep** [comment]
Hi Andy, 

I'm probably mishandling your framework. If you want to have a look at what I did

 * deck.rb: http://pastebin.com/DTjpSuds
 * yaml file: http://pastebin.com/7JLcQ4qJ

In the excel file I currently have the different values and a bunch of "x" for non numeric values where I don't want to display anything.

Thanks, Tim

**Comment by andymeneely** [comment]
Sorry I'm just now returning to this. Those pastebin links aren't up anymore - are you still having issues with this? Is there something to change?
