### ISSUE TITLE
A way to enumerate layout entries

### ISSUE THREAD

**Issue by sparr** [andymeneely/squib#212]
I have :cut and :safe entries in many of my layouts, so I can preview cutting locations and margins.

For some components, these are `rect`s, rounded or not. For some other components, these are `circle`s.

Then there are components with complex dies that can't be represented by a single element (see #210 for a potential partial solution to this).

I'd like to make `:cut-1` `:cut-2` `:cut-bottomline` `:cut-foo` `:cut-000` and have some built in way to enumerate them or even loop through them.

(separately, I'd also love to just have an example of how to enumerate them with a ruby call; from the unit tests I know the layout data is accessible, I'm just not sure how)

**Comment by andymeneely** [comment]
So to enumerate layout entries you just do:

```ruby
Squib::Deck.new do
  use_layout: 'economy.yml'
  layout.each do |key, value|
    puts "Key #{key}, value: #{value}"
  end
end
```

To loop over layouts you can do something like this:

```ruby
%w(cut-1 cut-2 cut-foo).each do |cut_layout|
  rect layout: cut_layout
end
```

**Comment by sparr** [comment]
Is there a "best practices" way to let a layout specify what type of drawing element it should be? Off the top of my head I could call them cut-00-rect cut-01-circle cut-02-rect cut-03-polygon etc then do string manipulation on the keys, but that seems very hacky.

**Comment by andymeneely** [comment]
Sorry I didn't see this last comment. So the conceptual answer is that you start with what shape you want to draw, then draw what you need. So "draw all the circles on these spots" instead of "if it's this thing draw a circle".

Layouts are there to keep your styles readable and reusable. They're supposed to be groupings data, not logic. So I wasn't intending for logic of drawing to be in a layout.

That being said, Squib isn't really supposed to be a complex drawing program. The shapes are there for simple things, but when the drawings get complex you'll need to switch to SVG. 

Are you still having issues?

**Comment by sparr** [comment]
I haven't touched this recently, but I expect that it still remains non-trivial to implement cut and safe lines for components that aren't a trivial shape, where the cut line is actually made up of multiple different shapes.
