### ISSUE TITLE
trouble downloading

### ISSUE THREAD

**Issue by choboy11** [andymeneely/squib#232]
Hello, whenever I try to download I get this: 
```
RaviAir:~ ravi$ gem install squib
Building native extensions.  This could take a while...
ERROR:  Error installing squib:
	ERROR: Failed to build gem native extension.

    current directory: /Users/ravi/.rvm/gems/ruby-2.4.0/gems/cairo-1.15.9/ext/cairo
/Users/ravi/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20170809-18177-in757q.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/ravi/.rvm/rubies/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:299:in `parse_pc': .pc for zlib doesn't exist. (RuntimeError)
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:196:in `declaration'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:210:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:145:in `cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:212:in `block in collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:211:in `collect'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:211:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:145:in `cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:215:in `block in collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:214:in `collect'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:214:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:154:in `cflags_only_other'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:452:in `cflags_only_other'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:499:in `have_package'
	from extconf.rb:52:in `required_pkg_config_package'
	from extconf.rb:60:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ravi/.rvm/gems/ruby-2.4.0/extensions/x86_64-darwin-14/2.4.0/cairo-1.15.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ravi/.rvm/gems/ruby-2.4.0/gems/cairo-1.15.9 for inspection.
Results logged to /Users/ravi/.rvm/gems/ruby-2.4.0/extensions/x86_64-darwin-14/2.4.0/cairo-1.15.9/gem_make.out


```
and the log file contains this: 

```
checking for GCC... -------------------- yes

"gcc -o conftest -I/Users/ravi/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0/x86_64-darwin14 -I/Users/ravi/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0/ruby/backward -I/Users/ravi/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl@1.1/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe conftest.c  -L. -L/Users/ravi/.rvm/rubies/ruby-2.4.0/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl@1.1/lib -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl@1.1/lib     -lruby.2.4.0  -lpthread -lgmp -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -I/Users/ravi/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0/x86_64-darwin14 -I/Users/ravi/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0/ruby/backward -I/Users/ravi/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl@1.1/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: #ifndef __GNUC__
5: # error
6: |:/ === __GNUC__ undefined === /:|
7: #endif
/* end */

--------------------

checking for Win32 OS... -------------------- no

--------------------

have_package: checking for cairo version (>= 1.2.0)... -------------------- yes

--------------------

 

```
i'm not sure what to do, i've tried a few things from google like making sure Xcode commands are installed but i still have this issue.  Also i'm completely new to Ruby.

thank you for reading this

**Comment by andymeneely** [comment]
Do you get the same error when you do `gem install cairo`?

Are you using Homebrew? RVM? RBenv?

**Comment by andymeneely** [comment]
Does this comment fix it for you?

https://github.com/ruby-gnome2/ruby-gnome2/issues/259#issuecomment-59751807

We had an issue related to this recently, but I thought we had it worked out. Sorry that this is your first impression of Squib and Ruby - it usually works pretty easily on Macs.

**Comment by choboy11** [comment]
Hello andy, thanks for the reply.

I just tried <gem install cairo> and I got the same error 

<Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.>

I'm using homebrew and rvm

**Comment by andymeneely** [comment]
This was all fixed, right?

**Comment by choboy11** [comment]
Yes this was fixed. I will hit the close and comment button when I post this.

**Comment by RichCrook** [comment]
I am the same issue. Is there a resolution?

Thanks

**Comment by cjpsmith** [comment]
I was also having this problem, and I tried:

`PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig gem install gobject-introspection`

and then tried installing again with `gem install squib`, and that seemed to work

**Comment by Kyrremann** [comment]
Just wanted to mention that neither of these solutions worked for me.
Ended up just building my code in a docker container.

**Comment by andymeneely** [comment]
Hm. I don't know what to say - I can't reproduce it on my Mac. If you figure something out I'd be happy to hear an update.

**Comment by sammlapp** [comment]
I am experiencing the same issue of not being able to install the package with gem install squib or gem install cairo. I get the same errors as above. I am on OS X 10.14 and have tried using different versions of Ruby with the same result (also tried installing/updating developer tools as recommended in other threads).

**Comment by andymeneely** [comment]
@sammlapp Are you still having this issue? Are you using Homebrew?

**Comment by sammlapp** [comment]
I decided to use Python instead because it was not working for me. Yes, I was using Homebrew and tried rbenv and then uninstalled and tried RVM, but continued to have the same error.

**Comment by andymeneely** [comment]
Ok. I don’t think it’s an rbenv or rvm issue. I would love to get to the bottom of this if you’re willing to troubleshoot with me. If not for you then the next person.

**Comment by Kyrremann** [comment]
I can also help in debugging. Haven't used the gem for a long time, but as mention above, I ended up building the code in a Docker-container.

**Comment by andymeneely** [comment]
Ok good! Here's a barrage of questions:

If you do a fresh `gem install squib` now, do you get the same error? And can you show me the mkmf error again? (Just to make sure things didn't change)

Are you using homebrew?

What version of ruby?

rbenv, or rvm, or just built-in ruby?

**Comment by sammlapp** [comment]
I'm willing to spend an hour on it. I've already sunk a bunch of time and then realized I could just use some python I'm familiar with. 

I'm using hombrew, Ruby 2.6, and rvm. But I have also tried with rbenv and with different versions of Ruby. Here's my console output:

Sams-MacBook-Pro:kaboom samlapp$ brew -v
Homebrew 2.0.0-6-g8df3d20
Homebrew/homebrew-core (git revision dd6c6; last commit 2019-02-03)
Sams-MacBook-Pro:kaboom samlapp$ rvm -v
rvm 1.29.7 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
Sams-MacBook-Pro:kaboom samlapp$ rvm current
ruby-2.6.0
Sams-MacBook-Pro:kaboom samlapp$ gem install squib
Building native extensions. This could take a while...
ERROR:  Error installing squib:
	ERROR: Failed to build gem native extension.

    current directory: /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/cairo-1.15.13/ext/cairo
/Users/samlapp/.rvm/rubies/ruby-2.6.0/bin/ruby -I /Users/samlapp/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0 -r ./siteconf20190210-93268-jsq0et.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/samlapp/.rvm/rubies/ruby-2.6.0/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:305:in `parse_pc': .pc for gobject-2.0 doesn't exist. (RuntimeError)
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:196:in `declaration'
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:210:in `collect_cflags'
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:145:in `cflags'
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:212:in `block in collect_cflags'
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:211:in `collect'
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:211:in `collect_cflags'
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:154:in `cflags_only_other'
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:485:in `cflags_only_other'
	from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:532:in `have_package'
	from extconf.rb:52:in `required_pkg_config_package'
	from extconf.rb:60:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/samlapp/.rvm/gems/ruby-2.6.0/extensions/x86_64-darwin-18/2.6.0/cairo-1.15.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/cairo-1.15.13 for inspection.
Results logged to /Users/samlapp/.rvm/gems/ruby-2.6.0/extensions/x86_64-darwin-18/2.6.0/cairo-1.15.13/gem_make.out

**Comment by sammlapp** [comment]
The log file:

current directory: /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/cairo-1.15.13/ext/cairo
/Users/samlapp/.rvm/rubies/ruby-2.6.0/bin/ruby -I /Users/samlapp/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0 -r ./siteconf20190210-93268-jsq0et.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/samlapp/.rvm/rubies/ruby-2.6.0/bin/$(RUBY_BASE_NAME)
        --with-pkg-config
        --without-pkg-config
        --with-override-variables
        --without-override-variables

/Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:305:in `parse_pc': .pc for gobject-2.0 doesn't exist. (RuntimeError)
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:196:in `declaration'
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:210:in `collect_cflags'
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:145:in `cflags'
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:212:in `block in collect_cflags'
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:211:in `collect'
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:211:in `collect_cflags'
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:154:in `cflags_only_other'
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:485:in `cflags_only_other'
        from /Users/samlapp/.rvm/gems/ruby-2.6.0/gems/pkg-config-1.3.2/lib/pkg-config.rb:532:in `have_package'
    from extconf.rb:52:in `required_pkg_config_package'
        from extconf.rb:60:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/samlapp/.rvm/gems/ruby-2.6.0/extensions/x86_64-darwin-18/2.6.0/cairo-1.15.13/mkmf.log

extconf failed, exit code 1
~

**Comment by Kyrremann** [comment]
It worked fine now, but I'm pretty sure I spent some time last time I tried installing `cairo`. I'll try to uninstall `squib`, `cairo`, and some other dependencies, and try again.

```
$ gem install squib
Fetching: pkg-config-1.3.3.gem (100%)
Successfully installed pkg-config-1.3.3
Fetching: native-package-installer-1.0.6.gem (100%)
Successfully installed native-package-installer-1.0.6
Fetching: cairo-1.15.13.gem (100%)
Building native extensions. This could take a while...
Successfully installed cairo-1.15.13
Fetching: classy_hash-0.2.1.gem (100%)
Successfully installed classy_hash-0.2.1
Fetching: glib2-3.2.7.gem (100%)
Building native extensions. This could take a while...
Successfully installed glib2-3.2.7
Fetching: gobject-introspection-3.2.7.gem (100%)
Building native extensions. This could take a while...
Successfully installed gobject-introspection-3.2.7
Fetching: gio2-3.2.7.gem (100%)
Building native extensions. This could take a while...
Successfully installed gio2-3.2.7
Fetching: highline-1.7.10.gem (100%)
Successfully installed highline-1.7.10
Fetching: mercenary-0.3.6.gem (100%)
Successfully installed mercenary-0.3.6
Fetching: nokogiri-1.8.4.gem (100%)
Building native extensions. This could take a while...
Successfully installed nokogiri-1.8.4
Fetching: cairo-gobject-3.2.7.gem (100%)
Building native extensions. This could take a while...
Successfully installed cairo-gobject-3.2.7
Fetching: pango-3.2.7.gem (100%)
Building native extensions. This could take a while...
Successfully installed pango-3.2.7
Fetching: rubyzip-1.2.2.gem (100%)
Successfully installed rubyzip-1.2.2
Fetching: roo-2.7.1.gem (100%)
Successfully installed roo-2.7.1
Fetching: gdk_pixbuf2-3.2.7.gem (100%)
Building native extensions. This could take a while...
Successfully installed gdk_pixbuf2-3.2.7
Fetching: rsvg2-3.2.7.gem (100%)
Building native extensions. This could take a while...
Successfully installed rsvg2-3.2.7
Fetching: squib-0.14.2.gem (100%)
Successfully installed squib-0.14.2
Parsing documentation for pkg-config-1.3.3
Installing ri documentation for pkg-config-1.3.3
Parsing documentation for native-package-installer-1.0.6
Installing ri documentation for native-package-installer-1.0.6
Parsing documentation for cairo-1.15.13
Installing ri documentation for cairo-1.15.13
Parsing documentation for classy_hash-0.2.1
Installing ri documentation for classy_hash-0.2.1
Parsing documentation for glib2-3.2.7
Installing ri documentation for glib2-3.2.7
Parsing documentation for gobject-introspection-3.2.7
Installing ri documentation for gobject-introspection-3.2.7
Parsing documentation for gio2-3.2.7
Installing ri documentation for gio2-3.2.7
Parsing documentation for highline-1.7.10
Installing ri documentation for highline-1.7.10
Parsing documentation for mercenary-0.3.6
Installing ri documentation for mercenary-0.3.6
Parsing documentation for nokogiri-1.8.4
Installing ri documentation for nokogiri-1.8.4
Parsing documentation for cairo-gobject-3.2.7
Installing ri documentation for cairo-gobject-3.2.7
Parsing documentation for pango-3.2.7
Installing ri documentation for pango-3.2.7
Parsing documentation for rubyzip-1.2.2
Installing ri documentation for rubyzip-1.2.2
Parsing documentation for roo-2.7.1
Installing ri documentation for roo-2.7.1
Parsing documentation for gdk_pixbuf2-3.2.7
Installing ri documentation for gdk_pixbuf2-3.2.7
Parsing documentation for rsvg2-3.2.7
Installing ri documentation for rsvg2-3.2.7
Parsing documentation for squib-0.14.2
Installing ri documentation for squib-0.14.2
Done installing documentation for pkg-config, native-package-installer, cairo, classy_hash, glib2, gobject-introspection, gio2, highline, mercenary, nokogiri, cairo-gobject, pango, rubyzip, roo, gdk_pixbuf2, rsvg2, squib after 15 seconds
17 gems installed
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

**Comment by Kyrremann** [comment]
Tried again with removing all the dependencies, and it still works for me.

**Comment by andymeneely** [comment]
Ok, so one thing that I've noticed in the past is that the dependency tree for the native bindings related to `gobject-introspection` and `cairo-gobject` can get a little messed up. They're relatively new to the Cairo/Pango dependency tree (last year or so). We've [had issues exactly like this before](https://github.com/rcairo/rcairo/issues/49) and the fix came quickly. 

@Kyrremann Glad you got it to work! Super annoying that we don't really understand why.

@sammlapp try doing `gem install pkg-config` and take a look at the above thread

**Comment by peterusev** [comment]
Hi all,

Having the same issue when trying to install. ruby 2.6.1p33 with rbenv / mojave 10.14.3 / all of cairo, pango, nokogiri are installed. Here is what I see -- any thoughts on how I might resolve this?

`Building native extensions. This could take a while...
ERROR:  Error installing squib:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/cairo-1.15.13/ext/cairo
/usr/local/var/rbenv/versions/2.6.1/bin/ruby -I /usr/local/var/rbenv/versions/2.6.1/lib/ruby/2.6.0 -r ./siteconf20190309-81951-kt933y.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/var/rbenv/versions/2.6.1/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:319:in `parse_pc': .pc for libffi doesn't exist. (RuntimeError)
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:218:in `declaration'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:232:in `collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:167:in `cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:234:in `block in collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:233:in `collect'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:233:in `collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:167:in `cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:234:in `block in collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:233:in `collect'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:233:in `collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:176:in `cflags_only_other'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:488:in `cflags_only_other'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:535:in `have_package'
	from extconf.rb:52:in `required_pkg_config_package'
	from extconf.rb:60:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-18/2.6.0-static/cairo-1.15.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/cairo-1.15.13 for inspection.
Results logged to /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-18/2.6.0-static/cairo-1.15.13/gem_make.out
`
and here is the log

`checking for GCC... -------------------- yes

"clang -o conftest -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0/x86_64-darwin18 -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0/ruby/backward -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0 -I. -I/usr/local/var/rbenv/versions/2.6.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/usr/local/var/rbenv/versions/2.6.1/lib -L. -L/usr/local/var/rbenv/versions/2.6.1/lib  -fstack-protector-strong -L/usr/local/lib     -lruby.2.6-static -framework Security -framework Foundation -lpthread -ldl -lobjc   "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"clang -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0/x86_64-darwin18 -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0/ruby/backward -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0 -I. -I/usr/local/var/rbenv/versions/2.6.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: #ifndef __GNUC__
5: # error
6: |:/ === __GNUC__ undefined === /:|
7: #endif
/* end */

--------------------

checking for Win32 OS... -------------------- no

--------------------

have_package: checking for cairo version (>= 1.2.0)... -------------------- yes

--------------------
`
