### ISSUE TITLE
Exporting Rules.md as a pdf or image alongside with cards?

### ISSUE THREAD

**Issue by bcetin** [andymeneely/squib#280]
Is this functionality available in the current state of the project? I am new to ruby and could not find details in the documentation.

**Comment by andymeneely** [comment]
Squib doesn't have any features to render Rules.md to PDF. But, I do this myself in Ruby in my own projects. I use `wkhtmltopdf` as a command line tool for it. And then I use Kramdown to convert Markdown to HTML. It's a bit brittle because wkhtmltopdf is a bit unstable, which is why I don't "officially" support it as a feature of Squib.

You can see how I do this in my heist game:
  * https://github.com/andymeneely/project-timber-wolf/blob/master/Rakefile#L178-L196
  * https://github.com/andymeneely/project-timber-wolf/blob/master/src/rules.rb

I'm also experimenting with an approach to generating the PDF directly from HTML using the Prawn library. Here's my experiment with that:

https://github.com/andymeneely/project-bolt-rats/blob/master/lib/rules.rb

A more heavy-handed approach is to use [Pandoc](https://pandoc.org/). Years ago I tried that and had limited success, but I also hear that the project has really matured in recent years - so maybe that's the most turnkey solution.

Best of luck!!
