### ISSUE TITLE
Document and maybe integrate "blocks" or "cells" for easy grid layouts

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#294]
Heard about this neat little monkeypatch from @mzemel. This snippet: https://github.com/mzemel/whipped/blob/a31cd0fcb19223755e33b1edbc0f0343448134aa/deck.rb#L4-L14

So you can then align things like `3.blocks` in your code easily without doing multiplication in your head. 

At the very least, we could document this. 

We could also introduce a "block" or "cell" as a custom unit that defaults to 37.5. That way you can have a layout file that says:

```yml
cut:
  x: 1 cell
  y: 1 cell
```

**Comment by mzemel** [comment]
Hey @andymeneely, I've put together a "halfway" concept:

https://github.com/mzemel/squib/commit/44278beb29543302400feb44d136e4511d82dae9

Right now, it's looking like it'll be tricky to support `x: 2cells` in the layout file, since the layout parser doesn't have access to instance variables set in `deck.rb`

Here's an example of [`cells(2)`](https://github.com/mzemel/whipped/commit/c99a042361a6c982d68b29fe947a9734866df64c#diff-86acaa893e30d7a8df15b09146c6f335R31-R32) in a `deck.rb` file.  So that reads well...

But I'm not loving the asymmetry of a unit available in `deck.rb`, but not in `layout.yml`.  Also, it seems like the "squib way" is to put all/most options in the `layout.yml` file.

What are your thoughts?  Happy to move forward with a PR and call out the asymmetry in the documentation, or shelve it for another time :)

**Comment by qrunchmonkey** [comment]
big, big +1 on this issue.

I agree that having a different `cell_size ` in yaml vs. in ruby would a nightmare, and make this feature mostly worthless.

I haven't checked out the associated PR yet, but looking at how DPI is passed to `layout_parser.rb` , I don't see a good reason why the grid size couldn't be passed the same way. Conceptually DPI and cell size are the same kind of thing - both are a scaling factor applied to unit conversion. 

I'd encourage you to not complicate this by having non-square cells, gutters, or anything like that. This feature would be amazing for rapidly prototyping cards on graph paper and/or in code. It doesn't need to be anything more.

**Comment by andymeneely** [comment]
Yeah adding a custom unit shouldn't be hard at all. I'll be picking up my Squib work soon and will do something like this. And it'll work the same between yaml and ruby. You'll be able to modify the size of a "cell" as a config setting and it'll default to 75px or 1/8in.

**Comment by andymeneely** [comment]
This is going to be part of v0.16!
