### ISSUE TITLE
Markup for embedding icons in text

### ISSUE THREAD

**Issue by vusak** [andymeneely/squib#30]
It would be very useful to be able to embed images via <img> tags or some similar inline approach.

As a reference, nandeck provides this functionality with statements like:

HTMLIMAGE=,"(S)","art/icon.png",1,1,P
HTMLTEXT=,"some text with the (S) icon embedded",0,0,6,1,#ffffff,0,T

If there was markup available to embed images, then a string transform could be used to convert -  whatever arbitrary markup the designer chooses - into the appropriate tag with src/size data.

**Comment by andymeneely** [comment]
I've been looking into this.

It won't be with an HTML renderer. Adding in an HTML rendering engine would be a huge dependency to add. 

But, it looks like Pango does support embedded images, but the documentation is very skimpy. I know I can roll my own with some other well-documented Pango methods but I'd rather use their API for it if I can.

As for how to approach it syntax-wide. I have some ideas. The syntax might look something like:
```ruby
text(str: 'You may take 1 :bread:') do |context|
  context.svg embed: ':bread:', file: 'bread.svg'
end
```
The extra block to the `text` command would also be helpful for doing things like drawing a box behind text that fits to the text (currently you have to draw the text to get the ink extents, then draw the box, then draw the ink extents).

**Comment by vusak** [comment]
Im currently looking into this, and would love a pointer in the direction of the skimpy documentation you mentioned, bonus points if you have a specific technique in mind?

Conceptually Im stuck thinking this involves creating/splitting multiple layouts from the original one, or alternatively fudging fonts in some way, or possibly overlaying images; all of which seem clunky in different ways.

With regard to the context you see being passed into the block, is that likely to be a Pango::Context or CairoContextWrapper or even a PangoContextWrapper?

**Comment by andymeneely** [comment]
Alright, this is has been an obsessive Google hobby of mine over the past few weeks. Seriously, about five or six tabs are open on my phone at any given time. Here's my status.

It's disconcerting to see this email went unanswered, because it's exactly what we're looking for: https://www.ruby-forum.com/topic/1089448

I also came across these shape renderers and I think that's the way to go, but I don't know how to use the API. Here's the doc for the original C library: https://developer.gnome.org/pango/stable/pango-Cairo-Rendering.html#PangoCairoShapeRendererFunc

One tactic that I've been taking is doing GitHub searches for those API calls to Pango - mostly in C. I have seen some examples, but I'm still trying to understand how they work. 

As one workaround, I personally use icon fonts or the lesser-known UTF-8 symbols for prototyping purposes. For example, if I install FontAwesome on my system I can do something like this:

```ruby
require 'squib'
trash_icon = "<span font=\"FontAwesome\">\uF1F8</span> "
Squib::Deck.new do
  bonus = trash_icon + "Building"
  text str: bonus, markup: true  # shows up as Trash icon 
end
```

Now... this does not work well when you want to make/tweak your own icon. Inkscape does support making your own icon fonts out of your SVGs, but the process is convoluted and would still require you to re-install the font every time you change the icon. 

Or, as you say, we can carve out the space ourselves in the string and use Cairo to draw the image on top. Pango gives us the xy coordinates of any index of the string. The hard part is figuring out how much space to add and somehow adding it. I'm wondering if `set_geometry` is the way to adjust that, though. I'll take a look at that.

**Comment by andymeneely** [comment]
Ok, I have come up with a solution that just might work. It feels like a workaround, but I think it'll be reliable.

Tab stops.

Suppose we need to replace `:bread:` in `"You may take 2 :bread: from the pile"`. We use `layout.index_to_pos` to get the beginning of `:bread:`. We do a string substitution of `:bread:` to a tab character. Then set the tab stops to be the xy pos of the tab plus the width of the icon. We can have as many tab stops as we like. 

Now, embedded icons won't wrap as if they were normal glyphs. But that might just come with the territory until we come up with a better way. 

By the way, it took me a while to get tab stops working. If you want to play with them, here's a snippet to put in `lib/squib/graphics/text.rb`

```ruby
layout.tabs = Pango::TabArray.new(2,true,['left', 200], ['left', 519])
```
(and then put tab characters into your text string)

I'll start working on this feature. I see your experimental branch on the fork. I'll probably take a different approach than to add to the CairoContextWrapper, but I'll shoot for the above syntax.

**Comment by andymeneely** [comment]
An update

Tab stops won't work. Wrapping messes things up.

I delved deeper into Pango's inner libraries to figure out how to do it with set_geometry and whatnot. 

Then I saw this email and had an epiphany: https://mail.gnome.org/archives/gtk-i18n-list/2005-March/msg00010.html

Here's how the Pango markup works for setting up a single letter:

```ruby
require 'squib'

Squib::Deck.new do
  # Notice how the letter spacing goes on both sides of the exclamation point
  text str: 'Hello, world<span letter_spacing="100000">!</span>!', font: 'Sans 72',
       valign: :middle, align: :center, height: 1125, width: 825,
       markup: true

  save_png prefix: 'geometry_hack_'
end
```

So, all we do do is turn on markup for the string, replace the text key with one of those `<span>` tags, and voila! Way easier than diving deep into the sparsely documented bowels of Pango/FreeType/FontConfig.

I'll get back to work on this issue using this method.

**Comment by andymeneely** [comment]
An update: I've got most of this working locally. I'm having issues with right-aligned and center-aligned text, but everything else is working well. My hope is to get my tests finished soon and get that last issue resolved. 

At worst I'll release a new version so you can play with it and then show "known bug" warning if you try to embed on right-aligned and center-aligned text.

**Comment by pickfifteen** [comment]
In testing this on the dev branch, I noticed the embeds don't seem to respect valign. There also seems to be an issue when the embeds are within <i> tags in a markup-supported text. Finally, there seems to be an issue with word-wrap, where rendering of the surrounding text is confused if the icon would be the last or first thing on a wrapped line.

**Comment by andymeneely** [comment]
Thanks for testing it out! I'll get on it.

**Comment by andymeneely** [comment]
Vertical alignment is almost there. The other two issues are related I believe - had to do with a problem in how I determined which index to stick the icon into (got thrown off by other markup on or around the embed). 
  - [ ] Fix vertical alignment
  - [x] Fix index location issue

Also added little adjusters for the icons in case your icon is a little off.

Go ahead and try out the new commit:

**Comment by pickfifteen** [comment]
Tried it out, three comments besides the vertical issue (that looks to me like it's computing number of lines using the size of the text, not the size of the icons):

1) Icons directly next to each other seem to have spaces between them; I would expect them to abut.
2) Inserting an icon as the first element causes a strange shift to the left of the box, and inserting two abutting icons increases the shift. Three abutting icons there makes it go haywire.
3) I am still getting the wrapping issue. If you make the middle align example 'Middle align: Take 1 :tool::tool::tool:' , you will see the "1" does not print on the line that clearly has room for it.

**Comment by andymeneely** [comment]
As of 554e8457da059f0bcbbcb39fc275ef03d096490f, vertical align works. Had to do delay drawing of icons until after valign is computed. 

I see the wrapping issue now. I'm currently baffled. I have very little control over how wrapping is done in Pango.

The spacing was semi-intentional, although I agree with you that most people would expect the icons to abut. That space on either side is actually half the width of the space character in the current font. So, I *could* theoretically compute the size of a space character at that point in the text and subtract that from the spacing I'm creating to get the icons flush. That's currently easier said than done though - I've got some chicken and egg issues to work out compute that right.

I also see the issue with the first icon. I'll look into it.

- [ ] Icons should abut when there is no space between them.
- [ ] Some lines don't wrap when they should. e.g. `'Middle align: Take 1 :tool::tool::tool:'`
- [ ] When an icon is first in the string, it bleeds over the edge of text layout . e.g. `':tool: Take 1'`

**Comment by pickfifteen** [comment]
Some discoveries that might help, that I haven't been able to follow through to an end solution yet:

The inserted span seems to be half the expected width if it is the first or last element, as determined by applying color to the inserted span.

Inserting the Unicode codes for non-zero space or non-zero breaking character(&amp;#8203; and &amp;#8204;) in the string before the embed causes the embeds to appear farther back in the string than they should; the value being returned for rect is earlier for some reason. Perhaps this is related to the wrapping issue; or there may be a character to put in the span instead of the space that will behave better.

**Comment by andymeneely** [comment]
Thanks for the pull request! Nice solution.

I integrated it, and it works on my machine and on my Mac - but it failed on Travis (Linux). The error had to do with a non-invertible matrix, which probably had to do with some font backend that used matrices for scaling the path. I changed the character size to 1, which is 1/1024 of a pixel. I don't see a spot currently.

**Comment by andymeneely** [comment]
Noticed one issue: 

  - [ ] the `text_options` sample doesn't expand parameters quite right. Probably an issue with array expansion

**Comment by andymeneely** [comment]
...and nevermind. Looks like the font size of 1 works on Mac, but not Windows. The "a" characters show up easily.

**Comment by pickfifteen** [comment]
You're right about the ```text_options``` issue; all the objects in an expanded array are the same. While you could deal with this at the point of expansion, you could also just have a simple ```str=str.clone``` inside the ```process_embeds```, past the check for no embeds; I would think in the common case the majority of array-expanded text on a card is not going to have embeds, and if you made all separate objects for array-expanded text that aren't ever going to use them, there's some cost there.

The downside is the extra overhead of cloning strings in non-expanded arrays unnecessarily. I'm not familiar enough to know which will be less performant, though of course it will depend on the deck and its number of expanded and non-expanded, and with-embed and without-embed, texts. Also, it's possible array expansion of other elements being the same object could cause other issues in the future.

**Comment by andymeneely** [comment]
Yeah I'm less worried about the expansion at the moment (I think I know what's going on there). I'm more concerned about this InvalidMatrix error. Check out this error I get on Travis (and only Travis) when I use the font_size of zero: 

```
Squib samples should execute with no errors
Failure/Error: load sample
Cairo::InvalidMatrixError:
invalid matrix (not invertible)

# ./lib/squib/graphics/text.rb:173:in `rescue in block in text'
# ./lib/squib/graphics/text.rb:167:in `block in text'
# ./lib/squib/card.rb:51:in `yield'
# ./lib/squib/card.rb:51:in `use_cairo'
# ./lib/squib/graphics/text.rb:136:in `text'
# ./lib/squib/api/text.rb:50:in `block in text'
# ./lib/squib/api/text.rb:49:in `each'
# ./lib/squib/api/text.rb:49:in `text'
# ./samples/embed_text.rb:8:in `block in <top (required)>'
# ./lib/squib/deck.rb:80:in `instance_eval'
# ./lib/squib/deck.rb:80:in `initialize'
# ./samples/embed_text.rb:3:in `new'
# ./samples/embed_text.rb:3:in `<top (required)>'
# ./spec/samples/samples_regression_spec.rb:18:in `load'
# ./spec/samples/samples_regression_spec.rb:18:in `block (3 levels) in <top (required)>'
# ./spec/samples/samples_regression_spec.rb:17:in `each'
# ./spec/samples/samples_regression_spec.rb:17:in `block (2 levels) in <top (required)>'
# ./spec/samples/samples_regression_spec.rb:10:in `block (3 levels) in <top (required)>'
# ./spec/samples/samples_regression_spec.rb:9:in `chdir'
# ./spec/samples/samples_regression_spec.rb:9:in `block (2 levels) in <top (required)>'
```

So that's when we run `embed_text.rb`. We get the error when an SVG icon is rendered, but the only factor that actually makes this fail is having the font size be zero. (see 5c4d7c368feddcb0149574d133fddf901c402df2).

I'm wondering if Pangocairo uses a transformation matrix that gets set to zero when the font size is zero. But I can't get it with save/restore. I haven't tried storing the matrix pre-embeds and then setting it back again.

**Comment by pickfifteen** [comment]
For future reference, I ran a test on Windows and found sizes 1-383 showed up as legible "a"'s; 384+ was only a pixel large, but it was visible and also large enough to take up horizontal space.

I don't know anything about the Pangocairo stuff, but there's always choosing 1 or 0 based off of ```RUBY_PLATFORM``` or ```CONFIG``` if no other solutions work.

**Comment by andymeneely** [comment]
Interesting. Why 384? It's got to be different Pango markup parsers thinking it's a "pango size" or "device size". I know if we modify via the api, there are different api calls, but I haven't figured out how to set letter spacing using the api.

**Comment by andymeneely** [comment]
Looks like this is done enough for release. I'll get #54 done and then push the new gem.
