### ISSUE TITLE
Some SVG Icons are distorted in output

### ISSUE THREAD

**Issue by hoverbird** [andymeneely/squib#87]
Hey there, loving this library so far! I ran into an issue on export. This occurs on Master of your Iconoclast project with no changes. Running `ruby deck.rb` succesfully outputs the three cards in data, but the icons are distorted on two cards. The same cards are problematic if I render them in a different order, and I've experimented with other icons from http://game-icons.net/ and seen the same sort of issue. Is this anything you've seen before?

![sheet_00](https://cloud.githubusercontent.com/assets/279/8440808/81cf543a-1f29-11e5-93b6-732296f969cc.png)

**Comment by andymeneely** [comment]
Yep - I have this problem myself. It only happens on Macs for me (which I use less frequently). I'm thinking it's a bug in libsrvg, but I'm trying to get a minimal example.

**Comment by hoverbird** [comment]
Gotcha— I'll try to stick to .PNGs for my project for now. Let me know if you need any help testing different versions of libsrvg, or whatever! And thanks for the speedy response.

**Comment by andymeneely** [comment]
Ok I've debugged this, wrote a sweet workaround, and then found that it's a bug already fixed in librsvg from like two years ago. But Macs seem to ship with the older version. My Mac had librsvg 2.36.3, but when I upgrade to the latest (2.40.9) the problem goes away. So, if you've got Homebrew, all you need to do is:

```sh
$ brew update
$ brew upgrade librsvg
```

I'll write up *exactly* what's going on a little later tonight. It's a fun bug.

This isn't the first time I've seen Macs ship with old, sometimes deprecated libraries. Grrr....

**Comment by andymeneely** [comment]
Here's the longer explanation. I took the `spade` GameIcon and hardcoded it into a Squib script since it's relatively simple. I went through the SVG path data and added some spaces and newlines to make it more readable. I then noticed stuff like `200-1.2`, which literally means "the x,y coordinate 200, 1.2". The GameIcons folks just remove the spaces to compress the file. 

Well, there are some numbers that get compressed into something like `123.45.67`, which were getting parsed wrong. When I introduced a clarifying space (i.e. `123.45 .67`), it all works. 

I even wrote a regex to work around it if the librsvg folks hadn't found and fixed this bug long ago. Here's my script for posterity:

```ruby
require 'squib'

Squib::Deck.new do
  svg_str = <<-EOSVG
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M0 0h512v512H0 z "/><path d="
  M 173.844 15.563 
  v .03l52.22 192.157
  c 7.035 -3.16 14.752 -6.03 22.686 -8.406 8.894 -2.663 18.006 -4.683 26.72 -5.72
  L 227 15.565
  l -53.156 -.002 
  z

  m 240.03 183.968
  c -13.045 15.41 -48.86 31.746 -91.874 45.845 1.64 16.418 2.707 35.075 2.72 53.344.01 18.658 -1.105 36.594 -4.25 51.155 -1.574 7.28 -3.61 13.75 -6.75 19.28 -3.143 5.53 -7.815 10.59 -14.564 12.376 -6.75 1.786 -13.316 -.275 -18.812 -3.5 -5.497 -3.223 -10.55 -7.79 -15.594 -13.31 -10.087 -11.045 -20.125 -26.058 -29.563 -42.22 -9.477 -16.23 -18.235 -33.37 -25.218 -48.688 -45.532 8.43 -85.193 11.69 -102.126 6.313 27.59 101.65 71.632 175.738 120.312 216.094
  H 388.75
  c 47.247 -52.587 62.203 -160.075 25.125 -296.69 
  z

  m  -127.843 12.064
  c -.745, .007 -1.525, .022 -2.31.062 -8.694.44 -19.32 2.508 -29.626 5.594 -10.308 3.086 -20.344 7.183 -28.063 11.313 -5.254 2.81 -8.667 5.522 -10.905 7.53 5.213 15.886 19.636 48.602 36.22 77 9.044 15.492 18.7 29.674 27.218 39 4.258 4.664 8.254 8.075 11.218 9.813 2.965 1.74 4.307 1.64 4.595 1.563.288 -.077 1.42 -.62 3.094 -3.564 1.67 -2.944 3.424 -7.837 4.75 -13.97 2.648 -12.262 3.823 -29.34 3.81 -47.217 -.02 -33.398 -4.27 -69.712 -7.842 -85.564 -2.73 -.895 -6.933 -1.61 -12.157 -1.562 
  z

   " fill="#fff"/></svg>
EOSVG

  # Workaround: add a space when there's three numbers
  # svg_str.gsub!(/(\d+\.\d+)(\.\d+)/, '\1 \2')

  svg data: svg_str
  save_png
end
```

But, in the end, just upgrade librsvg and you'll be fine.

**Comment by andymeneely** [comment]
I think I'll just recommend that people upgrade their librsvg if this comes up again.
